import { HttpService } from '@app/front/core/httpService'
import { AuthProvider } from '@app/front/provider/AuthProvider'
import { User } from '@prisma/client'
import { getCookie } from 'cookies-next/server'
import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'
import React from 'react'

export const metadata = {
  title: 'Welcome to front',
  description: 'Generated by create-nx-workspace',
}

const fetchUser = async () => {
  try {
    const token = await getCookie('auth_token', { cookies })
    if (!token) {
      return undefined
    }

    return await HttpService.get<User>('/api/user/me', {
      Cookie: `auth_token=${token}`,
    })
  } catch (error) {
    return undefined
  }
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const user = await fetchUser()

  if (!user) {
    redirect('/auth/signin')
  }

  return <AuthProvider user={user}>{children}</AuthProvider>
}
