import './global.css'
import ReactQueryProvider from '../provider/ReactQueryProvider'

export const metadata = {
  title: 'Welcome to front',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ReactQueryProvider>
  )
}
