import './global.css'
import { ToastProvider } from '@app/front/provider/ToastProvider'
import React from 'react'
import ReactQueryProvider from '../provider/ReactQueryProvider'

export const metadata = {
  title: 'Welcome to front',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body>
          <ToastProvider>{children}</ToastProvider>
        </body>
      </html>
    </ReactQueryProvider>
  )
}
